version: '3.7'

services: 
  # db:
  #   image: mysql:5.7
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   environment:
  #     MYSQL_ROOT_PASSWORD: tachikawa
  #     MYSQL_DATABASE: sample
  #     MYSQL_PASSWORD: tachikawa
  #   ports:
  #     - 4306:3306
  #   volumes:
  #     - mysql-db:/var/lib/mysql # mysql-dbのデータをvar/lib/mysqlに同期
  db:
    image: postgres
    ports:
      - 4306:3306
    volumes:
      - ./tmp/db:/var/lib/postgresql/data #MacOSの場合
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'tachikawa'
    restart: always
  api:
    tty: true
    depends_on: # dbに接続する記述
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    command: rails server -b 0.0.0.0 #はIPアドレスのバインド
  front: 
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
    command: 'yarn dev'
    ports:
      - "8000:3000"
volumes:
  postgresql-data:
    driver: local
